# -*- coding: utf-8 -*-
"""Internal_Chatbot_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YcYoGjWgnaqbfpuC3xXkJNEmr9cQ9th6
"""

pip install fastapi streamlit langchain-community sentence-transformers chromadb pandas langchain-chroma

!git clone https://github.com/springboardmentor441p-coderr/Fintech-data.git Fintech-data-main

!ls Fintech-data-main

role_access_mapping = {
    "Finance": ["Finance", "C-Level"],
    "marketing": ["Marketing", "C-Level"],
    "HR": ["HR", "C-Level"],
    "engineering": ["Engineering", "C-Level"],
    "general": ["Finance", "Marketing", "HR", "Engineering", "C-Level", "General"]
}

from langchain_community.document_loaders import TextLoader, CSVLoader
from pathlib import Path

file_path = Path("Fintech-data-main") / "engineering" / "engineering_master_doc.md"
loader = TextLoader(str(file_path), encoding="utf-8", autodetect_encoding=True)


docs = loader.load()
print(docs)

from pathlib import Path
from langchain_community.document_loaders import TextLoader, CSVLoader

DATA_ROOT = Path("Fintech-data-main")
all_documents = []

for department, roles in role_access_mapping.items():
    dept_path = DATA_ROOT / department

    for file in dept_path.glob("*"):


        if file.suffix == ".md":
            loader = TextLoader(str(file), encoding="utf-8")
        elif file.suffix == ".csv":
            loader = CSVLoader(str(file))
        else:
            continue

        docs = loader.load()

        for d in docs:
            d.page_content = clean_text(d.page_content)


        for d in docs:
            d.metadata = {
                "department": department,
                "allowed_roles": roles,
                "source": file.name
            }

        all_documents.extend(docs)

print("Total loaded documents:", len(all_documents))
print("Sample metadata:", all_documents[0].metadata)

import re

def clean_text(text):
    text = text.lower()
    text = re.sub(r"\s+", " ", text)
    text = re.sub(r"[^a-z0-9\s.,]", "", text)
    return text.strip()

import langchain
from langchain_text_splitters import RecursiveCharacterTextSplitter

text_splitter = RecursiveCharacterTextSplitter(
    separators=["\n\n", "\n", ".", " "],
    chunk_size=500,
    chunk_overlap=50,
    length_function=len
)

chunks = text_splitter.split_documents(all_documents)

print("Total chunks:", len(chunks))
print("Sample chunk metadata:", chunks[0].metadata)

from langchain_community.vectorstores import Chroma
from langchain_community.embeddings import HuggingFaceEmbeddings

embedding_model = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)


for chunk in chunks:
    if isinstance(chunk.metadata.get('allowed_roles'), list):
        chunk.metadata['allowed_roles'] = ",".join(chunk.metadata['allowed_roles'])


vector_db = Chroma.from_documents(
    documents=chunks,
    embedding=embedding_model,
    persist_directory="./chroma_db"
)

!ls chroma_db

query = "What is our quarterly revenue and financial performance?"

hr_filter = {
    "allowed_roles": { "$eq": "HR" }
}

results = vector_db.similarity_search(query, k=3, filter=hr_filter)

print(f"Query: {query}")
print(f"User Role: HR")
print(f"Results found: {len(results)}")

if len(results) == 0:
    print("Access Denied. HR users cannot see Finance data.")
else:
    print("Sensitive data was leaked!")

finance_filter = {
    "allowed_roles": { "$eq": "Finance,C-Level" }
}

authorized_results = vector_db.similarity_search(query, k=3, filter=finance_filter)

print(f"\nQuery: {query}")
print(f"User Role: Finance")
print(f"Results found: {len(authorized_results)}")

if len(authorized_results) > 0:
    print("Data retrieved for authorized user.")

test_roles = ["HR", "Engineering", "Marketing", "Finance", "C-Level", "General"]
finance_query = "What is our quarterly revenue and financial performance?"

print(f"--- SECURITY AUDIT: {finance_query} ---")

role_to_allowed_strings = {}
all_unique_allowed_role_metadata_strings = set()
for roles_list_from_mapping in role_access_mapping.values():
    all_unique_allowed_role_metadata_strings.add(",".join(roles_list_from_mapping))

for single_role_to_test in test_roles:
    matching_allowed_strings = []
    for allowed_role_metadata_str in all_unique_allowed_role_metadata_strings:
        if single_role_to_test in allowed_role_metadata_str.split(','):
            if single_role_to_test not in ["Finance", "C-Level"] and "Finance" in allowed_role_metadata_str.split(','):
                continue
            matching_allowed_strings.append(allowed_role_metadata_str)
    role_to_allowed_strings[single_role_to_test] = matching_allowed_strings

for role in test_roles:
    allowed_strings_for_this_role = role_to_allowed_strings.get(role, [])

    if role not in ["Finance", "C-Level"]:
        allowed_strings_for_this_role = ["__NO_MATCH_POSSIBLE__"]

    if not allowed_strings_for_this_role:
        role_filter = {"allowed_roles": {"$in": ["__NO_MATCH_PLACEHOLDER__"]}}
    else:
        role_filter = {"allowed_roles": {"$in": allowed_strings_for_this_role}}

    test_results = vector_db.similarity_search(finance_query, k=3, filter=role_filter)

    expected_to_find_results = (role == "Finance" or role == "C-Level")

    if expected_to_find_results:
        status = "ACCESS GRANTED" if len(test_results) > 0 else "FAILURE: No data found for authorized role"
    else:
        status = "ACCESS DENIED" if len(test_results) == 0 else "SECURITY LEAK DETECTED"

    print(f"Role: {role:<12} | Results: {len(test_results)} | Status: {status}")

"""# MILESTONE 2"""

import re

def preprocess_query(query):
    query = query.lower()
    query = re.sub(r"[^a-z0-9\s]", "", query)
    query = re.sub(r"\s+", " ", query).strip()
    return query

def python_rbac_filter(docs, user_role):
    allowed_docs = []
    blocked_docs = []

    for doc in docs:
        allowed_roles_str = doc.metadata.get("allowed_roles", "")
        allowed_roles = [r.strip() for r in allowed_roles_str.split(",")]

        if user_role in allowed_roles:
            allowed_docs.append(doc)
        else:
            blocked_docs.append(doc)

    return allowed_docs, blocked_docs

def log_chunks(query, role, raw_docs, allowed_docs, blocked_docs):
    print("\n" + "=" * 70)
    print("QUERY:", query)
    print("ROLE:", role)

    print("\n--- RAW RETRIEVED CHUNKS ---")
    for i, doc in enumerate(raw_docs):
        print(f"\n[RAW {i+1}]")
        print("Source:", doc.metadata.get("source"))
        print("Department:", doc.metadata.get("department"))
        print("Allowed Roles:", doc.metadata.get("allowed_roles"))
        print("Content:", doc.page_content[:300])

    print("\n--- BLOCKED BY RBAC ---")
    for i, doc in enumerate(blocked_docs):
        print(f"\n[BLOCKED {i+1}]")
        print("Source:", doc.metadata.get("source"))
        print("Department:", doc.metadata.get("department"))
        print("Allowed Roles:", doc.metadata.get("allowed_roles"))

    print("\n--- FINAL ALLOWED CHUNKS ---")
    for i, doc in enumerate(allowed_docs):
        print(f"\n[ALLOWED {i+1}]")
        print("Source:", doc.metadata.get("source"))
        print("Department:", doc.metadata.get("department"))
        print("Allowed Roles:", doc.metadata.get("allowed_roles"))
        print("Content:", doc.page_content[:300])

    print("=" * 70 + "\n")

def run_role_based_query():
    query = input("Enter your query: ").strip()
    role = input("Enter your role (HR / Engineering / Finance / Marketing / C-Level/ General): ").strip()

    if not query or not role:
        print("Query and role are required.")
        return

    query = preprocess_query(query)

    raw_docs = vector_db.similarity_search(query, k=5)

    allowed_docs, blocked_docs = python_rbac_filter(raw_docs, role)

    log_chunks(query, role, raw_docs, allowed_docs, blocked_docs)

    if not allowed_docs:
        print("ACCESS DENIED OR NO RELEVANT DATA FOUND")
        return

    print("\n--- FINAL ANSWER CONTEXT ---")
    for doc in allowed_docs:
        print(doc.page_content[:300])

run_role_based_query()

run_role_based_query()

run_role_based_query()
